name: price-scraper-pipeline

on:
  push:
    branches: [ main ]         # Build only on push to main
  schedule:
    - cron: "0 */8 * * *"       # Run scraper every 8 hours UTC
  workflow_dispatch:             # Allow manual build or manual run

jobs:

  build_and_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./price-scraper-notifier
          file: ./price-scraper-notifier/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move updated cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache


  run_scraper:
    name: Run scraper
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest image
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "Using image: $IMAGE"
          docker pull "$IMAGE:latest"

      - name: Run scraper with secrets
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "Running with: $IMAGE"

          docker run --rm \
            -e API_TOKEN="${{ secrets.API_TOKEN }}" \
            -e CHAT_ID="${{ secrets.CHAT_ID }}" \
            -e SHEET_ID="${{ secrets.SHEET_ID }}" \
            -e GOOGLE_CREDS="${{ secrets.GOOGLE_CREDS }}" \
            "$IMAGE:latest"
