name: price-scraper-pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */8 * * *"  # every 8 hours UTC
  workflow_dispatch:

jobs:

  build_and_push:
    if: github.event_name == 'push'
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./price-scraper-notifier
          file: ./price-scraper-notifier/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:build-${{ github.run_number }}
          no-cache: true

      - name: Save built tag for scheduler
        run: echo "build-${{ github.run_number }}" > image_tag.txt

      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest_image_tag
          path: image_tag.txt


  run_scraper:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    name: Run scraper container
    runs-on: ubuntu-latest

    steps:
      - name: Download last image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: latest_image_tag

      - name: Read image tag
        id: read_tag
        run: echo "tag=$(cat image_tag.txt)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull specific tagged image
        run: |
          echo "Using image tag: ${{ steps.read_tag.outputs.tag }}"
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.read_tag.outputs.tag }}

      - name: Debug env in container
        run: |
          docker run \
            --env GOOGLE_CREDS="${{ secrets.GOOGLE_CREDS }}" \
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.read_tag.outputs.tag }} python3 - << 'EOF'

      - name: Run scraper with secrets
        run: |
          docker run \
            --env API_TOKEN="${{ secrets.API_TOKEN }}" \
            --env CHAT_ID="${{ secrets.CHAT_ID }}" \
            --env SHEET_ID="${{ secrets.SHEET_ID }}" \
            --env GOOGLE_CREDS="${{ secrets.GOOGLE_CREDS }}" \
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.read_tag.outputs.tag }}
